backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    extension: mdx
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "navigation-pages",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Key", name: "key", widget: "string" }
      - { label: "ParentKey", name: "parentKey", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - label: "Points"
        name: "points"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Point", name: "point", widget: "markdown" }
