backend: 
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    extension: mdx
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "navigation-pages"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "navigationPages"
    label: "Navigation Pages"
    folder: "src/pages/navigationPages"
    create: true
    extenstion: mdx
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "navigation-pages"}
      - {label: "Title", name: "title", widget: "string"}
      - name: "section"
        label: "Section"
        widget: "relation"
        collection: "pages"
        displayFields: 
          - "title"
        searchFields: 
          - "title"
        valueField: "title"
  - name: "contentPages"
    label: "Content Pages"
    folder: "src/pages/contentPages"
    create: true
    extension: mdx
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "navigation-pages"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - name: "section"
        label: "Section"
        widget: "relation"
        collection: "pages"
        displayFields: 
          - "title"
        searchFields: 
          - "title"
        valueField: "title"
      - name: "relatedContent"
        label: "Related Content"
        widget: "list"
        field:
          - name: "content"
            label: "Content"
            widget: "relation"
            collection: "contentPages"
            displayFields: 
              - "title"
            searchFields: 
              - "title"
            valueField: "title"
      - label: "Points"
        name: "points"
        widget: "list"
        field: {label: Point, name: point, widget: markdown}